stages:
  - build

painted:
  stage: build
  image: nixos/nix
  script: |
    nix-env -iA nixpkgs.nixUnstable
    nix-env -iA nixpkgs.git # we need this for the flake
    echo 'experimental-features = nix-command flakes' >> /etc/nix/nix.conf
    nix build
    tar -cf result.tar.gz result/
  artifacts:
    paths:
      - /lincolnauster/painted/result/bin/painted
